### ISSUE TITLE
Issue fields

### ISSUE THREAD

**Issue by meengit** [shanehofstetter/youtrack-cli#16]
Hi!

Thank you very much for your excellent work.

Is it possible to access the fields of a project context when I do `youtrack  issue c`?

For example, we have the fields `state` and `sprints`. I try to create issues addressing these, but I can't find a working solution.

**Comment by shanehofstetter** [comment]
Hi @meengit,

I think this is possible only with the new rest api (current youtrack-cli uses the old one), which is getting implemented with #12 (still need to complete that one..). Then we also would need to provide functionality to enter custom field values when creating/updating an issue.

**Comment by meengit** [comment]
Hi @shanehofstetter 

Thank you very much for your prompt reply.
That's great! I look forward to it.

(I close this issue because it's answered.)
